/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2019-04-25 06:38:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fileupload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import fileupload.UtilMgr;
import java.text.DecimalFormat;
import fileupload.FileuploadBean;
import java.util.Vector;

public final class flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("fileupload.UtilMgr");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("fileupload.FileuploadBean");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- flist.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("EUC-KR");
      out.write('\r');
      out.write('\n');
      fileupload.FileuploadMgr mgr = null;
      mgr = (fileupload.FileuploadMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new fileupload.FileuploadMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
 
	Vector<FileuploadBean> vlist=mgr.listFile();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction allChk(){\r\n");
      out.write("\t\t\tf=document.frm;\r\n");
      out.write("\t\t\tif(f.allCh.checked){\r\n");
      out.write("\t\t\t\tfor(i=0;i<f.fch.length;i++){\r\n");
      out.write("\t\t\t\t\tf.fch[i].checked=true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tf.btn.disabled=false;//버튼의 활성화\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(i=0;i<f.fch.length;i++){\r\n");
      out.write("\t\t\t\tf.fch[i].checked=false;//버튼의 비활성화\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.btn.disabled=true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction chk(){\r\n");
      out.write("\t\t\tf=document.frm;\r\n");
      out.write("\t\t\tfor(i=0;i<f.fch.length;i++){\r\n");
      out.write("\t\t\t\tif(f.fch[i].checked){\r\n");
      out.write("\t\t\t\t\tf.btn.disabled=false;\r\n");
      out.write("\t\t\t\t\treturn;//fch가 한개가 체크가 되었기 때문에 나머지는 의미 없음. \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.btn.disabled=true;//fch에 체크된것이 하나도없을 경우 버튼 비활성화\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<h2>File List</h2>\r\n");
      out.write("<form name=\"frm\" action=\"fdeleteProc.jsp\">\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"checkbox\" name=\"allCh\" onclick=\"allChk()\"></td>\r\n");
      out.write("\t\t<td>번호</td>\r\n");
      out.write("\t\t<td>파일명</td>\r\n");
      out.write("\t\t<td>파일크기</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

			for(int i=0;i<vlist.size();i++){
				FileuploadBean bean =vlist.get(i);
				int num =bean.getNum();
				String upFile=bean.getUpfile();
				int szie=bean.getSize();
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"fch\" value=\"");
      out.print(num);
      out.write("\" onclick=\"chk()\"></td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(i+1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"fdownload.jsp?upFile=");
      out.print(upFile);
      out.write('"');
      out.write('>');
      out.print(upFile);
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(UtilMgr.monFormat(bean.getSize()));
      out.write("byte</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t");
}//--for
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"btn\" value=\"DELETE\" disabled>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"hidden\" name=\"fch\" value=\"0\">\r\n");
      out.write("</form><p/>\r\n");
      out.write("<a href=\"fupload.jsp\">입력폼</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
